version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["__APP__"]

    [main.main]
        [main.main.auth_mode]
        type = "select"
        ask.en = "Authentication feature ?"
        ask.fr = "Mode d'authentification?"
        choices = ["forced", "default"]
        bind = "FeatureAuthentication:__INSTALL_DIR__/server/plikd.cfg"