#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "plik"
name = "Plik"
description.en = "Plik is a temporary file upload system (Wetransfer like) in Go."
description.fr = "Application de partage de fichiers temporaires écrite en Go"

version = "1.4.2~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "MIT"
demo = "https://plik.root.gg"
admindoc = "https://root-gg.github.io/plik"
userdoc = "https://root-gg.github.io/plik"
code = "https://github.com/root-gg/plik"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64","arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/plik"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Choose the admin passwword for this app"
    help.fr = "Choisissez un mot de passe pour l'administrateur de cette application"
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/root-gg/plik/releases/download/1.4.2/plik-1.4.2-linux-amd64"    
    amd64.sha256 = "cc3a999183233ce9ebb166158cbf144073ddfe8d598a779f7b51088a3495e9dc"
    arm64.url = "https://github.com/root-gg/plik/releases/download/1.4.2/plik-1.4.2-linux-arm64"    
    arm64.sha256 = "fbe29bd70047e4d05304d37f84451b79d45b9652686a0750243e31258744b96f"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^plik-.*-linux-amd64$"
    autoupdate.asset.arm64 = "plik-.*-linux-arm64$"

    in_subdir = false
    rename = "plik"
    
    [resources.system_user]
    
    [resources.install_dir]
 

    [resources.data_dir]
    subdirs = ["files"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
