#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "plik"
name = "Plik"
description.en = "Plik is a temporary file upload system (Wetransfer like) in Go."
description.fr = "Application de partage de fichiers temporaires écrite en Go"

version = "1.4.2~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "MIT"
demo = "https://plik.root.gg"
admindoc = "https://root-gg.github.io/plik"
userdoc = "https://root-gg.github.io/plik"
code = "https://github.com/root-gg/plik"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64","arm64", "arm"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/plik"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "string"
    ask.en = "Admin name"
    ask.fr = "Nom pour l'administrateur"
    help.en = "Choose the admin name for this app (min. 4 characters)"
    help.fr = "Choisissez un nom pour l'administrateur de cette application (min. 4 caractères)"

    [install.auth_mode]
    ask.en = "Enable authentication to share files ?"
    ask.fr = "Activer l'authentification pour le partage de fichiers ?"
    type = "select"
    choices = ["forced", "default"]
    default = "forced"
    help.en = "forced -> no anonymous upload / default -> anonymous and authenticated upload"
    help.fr = "forced -> pas de téléchargement anonyme / default -> téléchargement anonyme et authentifié possible"
    

[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/root-gg/plik/releases/download/1.4.2/plik-server-1.4.2-linux-amd64.tar.gz"
    amd64.sha256 = "328cd739f198f5ca40e5010e61ed6f8a70d5a18d7418b8b543bab1710c92dc61"

    arm64.url = "https://github.com/root-gg/plik/releases/download/1.4.2/plik-server-1.4.2-linux-arm64.tar.gz"
    arm64.sha256 = "3d34af4826de4d3d19c6b9591e0730e8a2e8f80bf65650fe29b780b9b0f4b787"

    arm.url = "https://github.com/root-gg/plik/releases/download/1.4.2/plik-server-1.4.2-linux-arm.tar.gz"
    arm.sha256 = "0feb9f53a93888481fd7e5a41a3fe9fbad25ded348a2a2c520f09892f853d72f"



    autoupdate.asset.amd64 = "linux-amd64.tar.gz"
    autoupdate.asset.arm64 = "linux-arm64.tar.gz"
    autoupdate.asset.arm = "linux-arm.tar.gz"

    autoupdate.strategy = "latest_github_release"

    in_subdir = 1
    rename = "plik"

    [resources.system_user]
    
    [resources.install_dir]
 

    [resources.data_dir]
    subdirs = ["files"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql libpq-dev"

    [resources.ports]

    [resources.database]
    type = "postgresql"
	